# TravisCI configuration for php-stubs/wordpress-tests-stubs
language: "php"
os:
  - "linux"
dist: "bionic"

php:
  # giacocorsiglia/stubs-generator does not support PHP 7.0
#  - "8.0"
  - "7.4"
  - "7.3"
  - "7.2"
  - "7.1"

cache:
  directories:
    - "$HOME/.composer/cache"

before_install:
  - "phpenv config-rm xdebug.ini"
  - "composer self-update --1"
  - "composer validate --strict"

install:
  - "composer update --no-interaction --no-suggest"

before_script:
  - |
    if dpkg --compare-versions "$(phpenv version-name)" ge "7.4"; then
        echo "Hiding deprecated errors in generate-stubs ..."
        sed -i -e '3s/^/error_reporting(E_ALL ^ E_DEPRECATED);/' ./vendor/giacocorsiglia/stubs-generator/bin/generate-stubs
    fi

script:
  # Generate stubs
  - "bash -x ./generate.sh"
  # Check stubs syntax
  - "php -l wordpress-tests-stubs.php"
  # Check stubs changes compared to repository
  - "git diff --exit-code"
  # Execute stubs
  - "composer require --dev phpunit/phpunit:^7"
  - |
    php -r 'require "vendor/autoload.php"; class WP_Block_Type {}; require "wordpress-tests-stubs.php";'
